routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

$routes = ['only' => ['index', 'show', 'create', 'store', 'edit', 'update', 'destroy']];

Route::group(
[
    'prefix' => LaravelLocalization::setLocale(),
    'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ]
], function() {
    Route::get('/', function () {
        return redirect()->route('login');
    });

    Auth::routes(['register' => false, 'reset' => false, 'verify' => false]);

    Route::get('/home', 'HomeController@index')->name('home');

    Route::middleware('auth')->group(function() {
        Route::namespace('Admin')->prefix('admin')->name('admin.')->middleware('can:manage')->group(function() {
            Route::resource('users', 'UsersController');
            Route::get('settings', 'UsersController@settings')->name('settings.website');
        });

        Route::namespace('User')->prefix('user')->name('user.')->group(function() {
            Route::get('settings', 'SettingsController@show')->name('settings.show');
            Route::get('settings/edit', 'SettingsController@edit')->name('settings.edit');
            Route::patch('settings', 'SettingsController@update')->name('settings.update');

            Route::middleware('can:edit')->group(function() {
                $edit = ['only' => ['create','store','edit','update']];

                Route::get('designations/{purchaseOrder}/cf-purchaseorder', 'DesignationsController@cf_purchaseorder')->name('designations.cf.purchase-order');
                Route::resource('designations', 'DesignationsController', $edit);
                Route::post('invoices/import', 'InvoicesController@import')->name('invoices.import');
                Route::resource('invoices', 'InvoicesController', $edit);
                Route::post('members/import', 'MembersController@import')->name('members.import');
                Route::resource('members', 'MembersController', $edit);
                Route::post('memberships/import', 'MembershipsController@import')->name('memberships.import');
                Route::resource('memberships', 'MembershipsController', $edit);
                Route::get('memberships/{invoice}/cf-invoice', 'MembershipsController@cf_invoice')->name('memberships.cf.invoice');
                Route::get('memberships/{member}/cf-member', 'MembershipsController@cf_member')->name('memberships.cf.member');
                Route::post('purchase-orders/import', 'PurchaseOrdersController@import')->name('purchase-orders.import');
                Route::resource('purchase-orders', 'PurchaseOrdersController', $edit);
                Route::post('receipted-invoices/import', 'ReceiptedInvoicesController@import')->name('receipted-invoices.import');
                Route::resource('receipted-invoices', 'ReceiptedInvoicesController', $edit);
            });

            Route::middleware('can:delete')->group(function() {
                $delete = ['only' => ['destroy']];

                Route::resource('designations', 'DesignationsController', $delete);
                Route::resource('invoices', 'InvoicesController', $delete);
                Route::resource('members', 'MembersController', $delete);
                Route::resource('memberships', 'MembershipsController', $delete);
                Route::resource('purchase-orders', 'PurchaseOrdersController', $delete);
                Route::resource('receipted-invoices', 'ReceiptedInvoicesController', $delete);
            });

            Route::middleware('can:read')->group(function() {
                $read = ['only' => ['index','show']];

                Route::resource('designations', 'DesignationsController', $read);
                Route::get('invoices/download/{invoice}', 'InvoicesController@download')->name('invoices.download');
                Route::get('invoices/export', 'InvoicesController@export')->name('invoices.export');
                Route::resource('invoices', 'InvoicesController', $read);
                Route::get('members/export', 'MembersController@export')->name('members.export');
                Route::resource('members', 'MembersController', $read);
                Route::get('memberships/export', 'MembershipsController@export')->name('memberships.export');
                Route::resource('memberships', 'MembershipsController', $read);
                Route::get('purchase-orders/export','PurchaseOrdersController@export')->name('purchase-orders.export');
                Route::resource('purchase-orders', 'PurchaseOrdersController', $read);
                Route::get('receipted-invoices/download/{receiptedInvoice}', 'ReceiptedInvoicesController@download')->name('receipted-invoices.download');
                Route::get('receipted-invoices/export', 'ReceiptedInvoicesController@export')->name('receipted-invoices.export');
                Route::resource('receipted-invoices', 'ReceiptedInvoicesController', $read);
            });
        });
    });
});

app/Membership.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Membership extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'id',
        'member_id',
        'invoice_id',
        'date',
        'type',
        'amount'
    ];

    public function member() {
        return $this->belongsTo('App\Member');
    }

    public function invoice() {
        return $this->belongsTo('App\Invoice');
    }
}

app/Http/Controllers/Admin/UsersController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Role;
use App\User;
use Auth;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Str;

class UsersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::where('id','<>',auth()->id())->get();
        return view('admin.users.index')->with([
            'users' => $users,
            'count_value' => $users->count()
        ]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function settings()
    {
        return view('admin.settings.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $roles = Role::all();
        return view('admin.users.edit', [
            'roles' => $roles
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'password' => 'required|string|min:8|confirmed'
        ]);

        $user = new User;
        $user->lastname = '';
        $user->firstname = '';
        $user->username = '';
        $user->email = '';
        $user->password = password_hash($request->password, PASSWORD_DEFAULT);
        $user->api_token = Str::random(60);
        return $this->update($request, $user);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        if ($user == Auth::user()) {
            return view('user.settings.show', [
                'user' => $user
            ]);
        }
        return view('admin.users.show')->with('user', $user);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        if ($user == Auth::user()) {
            return view('user.settings.edit', [
                'user' => $user
            ]);
        }
        $roles = Role::all();
        return view('admin.users.edit', [
            'user' => $user,
            'roles' => $roles
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        $request->validate([
            /*'id' => 'required|unique:App\User,id',*/
            'lastname' => 'required|min:2',
            'firstname' => 'required|min:2',
            'username' => 'required|unique:App\User,username,'.$user->id,
            'email' => 'required|email',
        ]);
        $user->save();

        $user->roles()->sync($request->roles);
        $user->lastname = $request->lastname;
        $user->firstname = $request->firstname;
        $user->username = $request->username;
        $user->email = $request->email;
        $user->save();

        return redirect()->route('admin.users.show', $user->id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        $user->roles()->detach();
        $user->delete();

        return redirect()->route('admin.users.index');
    }
}

app/Http/Controllers/User/DesignationsController.php
<?php

namespace App\Http\Controllers\User;

use App\PurchaseOrder;
use App\Designation;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class DesignationsController extends Controller
{
    public function validator($request)
    {
        return $request->validate(
            [
                //'id' => 'required',
                'purchase_order_id' => 'required',
                'name' => 'required',
                'unit_price' => 'required',
                'quantity' => 'required',
                'total_amount' => 'required',
                'note' => 'required'
            ]
        );
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $designations = Designation::all();
        return view('user.designations.index')->with([
            'designations' => $designations,
            'count_value' => $designations->count()
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('user.designations.edit');
    }

    public function cf_purchaseorder(PurchaseOrder $purchaseOrder)
    {
        $designation = new Designation;
        $designation->purchase_order_id = $purchaseOrder->id;
        return view('user.designations.edit')->with([
            'designation' => $designation,
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $designation = new Designation;
        return $this->update($request, $designation);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Designation  $designation
     * @return \Illuminate\Http\Response
     */
    public function show(Designation $designation)
    {
        return view('user.designations.show')->with([
            'designation' => $designation,
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Designation  $designation
     * @return \Illuminate\Http\Response
     */
    public function edit(Designation $designation)
    {
        return view('user.designations.edit')->with([
            'designation' => $designation,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Designation  $designation
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Designation $designation)
    {
        $this->validator($request);
        if (empty($designation->id)) {
            $designation->id = Designation::max('id') +1;
        }
        $designation->purchase_order_id = $request->purchase_order_id;
        $designation->name = $request->name;
        $designation->unit_price = $request->unit_price;
        $designation->quantity = $request->quantity;
        $designation->total_amount = $request->total_amount;
        $designation->note = $request->note;
        $designation->save();

        return redirect()->route('user.designations.show',$designation->id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Designation  $designation
     * @return \Illuminate\Http\Response
     */
    public function destroy(Designation $designation)
    {
        $designation->destroy($designation->id);
        return redirect()->route('user.purchase-orders.show',$designation->purchase_order_id);
    }
}

app/Http/Controllers/User/MembersController.php
<?php

namespace App\Http\Controllers\User;

use App\Exports\MembersExport;
use App\Imports\MembersImport;
use App\Http\Controllers\Controller;
use App\Member;
use App\Membership;
use Illuminate\Http\Request;
use Maatwebsite\Excel\Facades\Excel;

class MembersController extends Controller
{
    public function validator($request)
    {
        return $request->validate(
            [
                'lastname' => 'required',
                'firstname' => 'required',
                'login' => 'nullable',
                'email' => 'nullable',
                'address' => 'nullable',
                'employer' => 'nullable'
            ]
        );
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $members = Member::all();
        return view('user.members.index')->with([
            'members' => $members,
            'count_value' => $members->count()
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('user.members.edit');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $member = new Member;
        return $this->update($request, $member);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Member  $member
     * @return \Illuminate\Http\Response
     */
    public function show(Member $member)
    {
        $memberships = Membership::where('member_id', $member->id)->get();

        return view('user.members.show')->with([
            'member' => $member,
            'memberships' => $memberships,
            'count_value' => $memberships->count()
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Member  $member
     * @return \Illuminate\Http\Response
     */
    public function edit(Member $member)
    {
        return view('user.members.edit')->with([
            'member' => $member,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Member  $member
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Member $member)
    {
        $this->validator($request);

        $member->lastname = $request->lastname;
        $member->firstname = $request->firstname;
        $member->login = $request->login;
        $member->email = $request->email;
        $member->address = $request->address;
        $member->employer = $request->employer;
        $member->save();

        return redirect()->route('user.members.show', $member->id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Member  $member
     * @return \Illuminate\Http\Response
     */
    public function destroy(Member $member)
    {
        foreach ($member->memberships as $membership) {
            $membership->member()->dissociate();
        }
        $member->destroy($member->id);
        return redirect()->route('user.members.index');
    }

    /**
     * Download the resource collection in CSV format
     */
    public function export()
    {
        return Excel::download((new MembersExport()), 'members_'.date('ymdHis').'.csv');
    }

    /**
     * Import the resource in CSV format
     *
     * @param  \Illuminate\Http\Request  $request
     */
    public function import(Request $request)
    {
        if($request->hasFile('file')) {
            try {
                $path = $request->file('file')->getRealPath();
                Excel::import(new MembersImport, $path, null, \Maatwebsite\Excel\Excel::CSV);
            } catch (\Exception $e) {
                \Session::flash('error', $e->getMessage());
            }
        }
        return redirect()->route('user.members.index');
    }
}

resources/views/user/memberships/details.blade.php
<div class="details">
    <div>
        <p class="title">{{ trans_choice('common.membership', 1) }} : </p>
        <p class="value">{{ $membership->id }}</p>
    </div>
    <div>
        <p class="title">{{ trans_choice('common.member', 1) }} : </p>
        @isset ($membership->member)
            <a href="{{ route('user.members.show', $membership->member->id) }}" class="value">
                <p>
                    {{ $membership->member->firstname." ".$membership->member->lastname }}
                </p>
            </a>
        @endisset
    </div>
    @empty (($invoice ?? '') || ($receiptedInvoice ?? ''))
        <div>
            <p class="title">
                @isset ($membership->invoice_id)
                    @if (isset($membership->invoice) && $membership->invoice->receipted)
                        {{ trans_choice('common.receipted-invoice', 1) }} :
                    @else
                        {{ trans_choice('common.invoice', 1) }} :
                    @endif
                @endisset
            </p>
            <p class="value">
                @isset ($membership->invoice_id)
                    {{ $membership->invoice_id }}
                    @isset($membership->invoice)
                        <a href="{{ route('user.invoices.show', $membership->invoice_id) }}">
                            <img src="{{ asset('images/chain_icon.svg') }}" title="{{ trans_choice('common.link_to', 1, ['page' => trans_choice('common.invoice', 1)]) }}" alt="Link icon">
                        </a>
                    @endisset
                @endisset
            </p>
        </div>
    @endempty
    <div>
        <p class="title">{{ trans_choice('common.date', 1) }} : </p>
        <p class="value">{{ $membership->date }}</p>
    </div>
    <div>
        <p class="title">{{ trans_choice('common.type', 1) }} : </p>
        <p class="value">{{ $membership->type }}</p>
    </div>
    <div>
        <p class="title">{{ trans_choice('common.amount', 1) }} : </p>
        <p class="value">{{ $membership->amount }}</p>
    </div>


    <div class="options buttons_area">
        @can('edit')
            <a href="{{ route('user.memberships.edit', $membership->id) }}">
                <button class="edit">
                    @lang('buttons.edit')
                    <img src="{{ asset('images/edit_icon.svg') }}" alt="Edit icon">
                </button>
            </a>
        @endcan

        @can('delete')
            <form class="ico" method="POST" accept-charset="utf-8" action="{{ route('user.memberships.destroy', $membership->id) }}">
                @csrf
                @method('DELETE')
                <confirm_action text="true" src="{{ asset('images/delete_icon.svg') }}">
                </confirm_action>
            </form>
        @endcan
    </div>
</div>

resources/views/user/memberships/edit.blade.php
@extends('layouts.default')

@section('javascript')
    {{-- Put here all the links to scripts --}}
    <script src="{{ mix('js/app.js') }}" async defer></script>
@endsection

@section('css')
    {{-- Put here all the links to stylesheet --}}
    <link href="{{ asset('css/buttons.css') }}" rel="stylesheet">
    <link href="{{ asset('css/form.css') }}" rel="stylesheet">
@endsection

@section('content')
<div class="container_page">

    <header>
        <h1>
            @isset($membership->member)
                {{ trans_choice('common.membership_of', 1, ['user' => $membership->member->firstname." ".$membership->member->lastname]) }}
            @else
                @lang('common.membership_creation')
            @endisset
        </h1>
    </header>

    <main>
        <div class="db_infos">
            <form class="buttons_area" method="POST" accept-charset="utf-8">
                @csrf
                @if (Request::is('user/memberships/*/edit'))
                    @method('PATCH')
                @endif

                <autocomplete_members
                  error="@error('member_id') is-require @enderror"
                  label="{{ trans_choice('common.member', 1) }}"
                  resource="member"
                  value="{{ old('member_id', $membership->member_id ?? '') }}"
                  api_token="{{ Auth::user()->api_token }}">
                </autocomplete_members>
                @error('member_id')
                    <span role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror

                <autocomplete_data_id
                  error="@error('invoice_id') is-require @enderror"
                  label="{{ trans_choice('common.invoice', 1) }}"
                  resource="invoice"
                  value="{{ old('invoice_id', $membership->invoice_id ?? '') }}"
                  api_token="{{ Auth::user()->api_token }}">
                </autocomplete_data_id>
                @error('invoice_id')
                    <span role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror

                <div class="case_infos">
                    <label for="date" class="title">{{ trans_choice('common.date', 1) }} : </label>
                    <input type="date" id="date" name="date" class="@error('date') is-require @enderror" value="{{ old('date', $membership->date ?? date('Y-m-d')) }}" required>
                </div>
                @error('date')
                    <span role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror

                <autocomplete_data_type
                  error_amount="@error('amount') is-require @enderror"
                  error_type="@error('type_id') is-require @enderror"
                  label_amount="{{ trans_choice('common.amount', 1) }}"
                  label_type="{{ trans_choice('common.type', 1) }}"
                  resource="type"
                  value_amount="{{ old('amount', $membership->amount ?? '') }}"
                  value_type="{{ old('type', $membership->type ?? '') }}"
                  api_token="{{ Auth::user()->api_token }}">
                </autocomplete_data_type>
                @error('type_id')
                    <span role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
                @error('amount')
                    <span role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror

                <div>
                    <button type="submit" class="save" formaction="
                        @if (Request::is('user/memberships/*/edit'))
                            {{ route('user.memberships.update', $membership->id) }}
                        @else
                            {{ route('user.memberships.store') }}
                        @endif">
                        @lang('buttons.save')
                    </button>
                </div>
            </form>

            <form class="buttons_area" method="GET" accept-charset="utf-8">
                @csrf
                <button type="submit" class="cancel" formaction="
                    @if (Request::is('user/memberships/*/edit'))
                        {{ route('user.memberships.show', $membership->id) }}
                    @else
                        {{ route('user.memberships.index') }}
                    @endif">
                    @lang('buttons.cancel')
                </button>
            </form>
        </div>
    </main>
</div>
@endsection

resources/views/user/memberships/index.blade.php
@extends('layouts.default')

@section('javascript')
    {{-- Put here all the links to scripts --}}
    <script src="{{ mix('js/app.js') }}" async defer></script>
    <script type="text/javascript" src="{{ asset('js/tableFilter.js') }}"></script>
    <script type="text/javascript" src="{{ asset('js/tableSorter.js') }}"></script>
@endsection

@section('css')
    {{-- Put here all the links to stylesheet --}}
    <link href="{{ asset('css/buttons.css') }}" rel="stylesheet">
    <link href="{{ asset('css/modal.css') }}" rel="stylesheet">
    <link href="{{ asset('css/tables.css') }}" rel="stylesheet">
@endsection

@section('content')
<div class="container_page">

    <header>
        <h1>{{ trans_choice('common.membership', 2) }}</h1>
    </header>

    <main>
        @include('user.memberships.table')

        <div class="buttons_area">
            @can('edit')
                <a href="{{ route('user.memberships.create') }}">
                    <button class="create">
                        @lang('buttons.add')
                        <img src="{{ asset('images/plus_icon.svg') }}" alt="Plus icon">
                    </button>
                </a>

                <div class="file_color">
                    <form method="post" accept-charset="utf-8" enctype="multipart/form-data">
                        @csrf
                        <input type="file" name="file">
                        <button class="import no-margin" type="submit" formaction="{{ route('user.memberships.import') }}">
                            @lang('buttons.import')
                            <img src="{{ asset('images/plus_icon.svg') }}" alt="Plus icon">
                        </button>
                    </form>
                </div>
            @endcan

            @can('read')
                <a href="{{ route('user.memberships.export') }}">
                    <button class="export">
                        @lang('buttons.export')
                        <img src="{{ asset('images/download_icon.svg') }}" alt="Download icon">
                    </button>
                </a>
            @endcan
        </div>

    </main>
</div>
@endsection

resources/views/user/memberships/show.blade.php
@extends('layouts.default')

@section('javascript')
    {{-- Put here all the links to scripts --}}
    <script src="{{ mix('js/app.js') }}" async defer></script>
@endsection

@section('css')
    {{-- Put here all the links to stylesheet --}}
    <link href="{{ asset('css/buttons.css') }}" rel="stylesheet">
    <link href="{{ asset('css/modal.css') }}" rel="stylesheet">
    <link href="{{ asset('css/tables.css') }}" rel="stylesheet">
@endsection

@section('content')
<div class="container_page">

    <header>
        <h1>
            @isset($membership->member)
                {{ trans_choice('common.membership_of', 1, ['user' => $membership->member->firstname." ".$membership->member->lastname]) }}
            @else
                @lang('common.member_deleted')
            @endisset
        </h1>
    </header>

    <main>
        @include('user.memberships.details')
    </main>
</div>
@endsection