routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

$routes = ['only' => ['index', 'show', 'create', 'store', 'edit', 'update', 'destroy']];

Route::group(
[
    'prefix' => LaravelLocalization::setLocale(),
    'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ]
], function() {
    Route::get('/', function () {
        return redirect()->route('login');
    });

    Auth::routes(['register' => false, 'reset' => false, 'verify' => false]);

    Route::get('/home', 'HomeController@index')->name('home');

    Route::middleware('auth')->group(function() {
        Route::namespace('Admin')->prefix('admin')->name('admin.')->middleware('can:manage')->group(function() {
            Route::resource('users', 'UsersController');
            Route::get('settings', 'UsersController@settings')->name('settings.website');
        });

        Route::namespace('User')->prefix('user')->name('user.')->group(function() {
            Route::get('settings', 'SettingsController@show')->name('settings.show');
            Route::get('settings/edit', 'SettingsController@edit')->name('settings.edit');
            Route::patch('settings', 'SettingsController@update')->name('settings.update');

            Route::middleware('can:edit')->group(function() {
                $edit = ['only' => ['create','store','edit','update']];

                Route::get('designations/{purchaseOrder}/cf-purchaseorder', 'DesignationsController@cf_purchaseorder')->name('designations.cf.purchase-order');
                Route::resource('designations', 'DesignationsController', $edit);
                Route::post('invoices/import', 'InvoicesController@import')->name('invoices.import');
                Route::resource('invoices', 'InvoicesController', $edit);
                Route::post('members/import', 'MembersController@import')->name('members.import');
                Route::resource('members', 'MembersController', $edit);
                Route::post('memberships/import', 'MembershipsController@import')->name('memberships.import');
                Route::resource('memberships', 'MembershipsController', $edit);
                Route::get('memberships/{invoice}/cf-invoice', 'MembershipsController@cf_invoice')->name('memberships.cf.invoice');
                Route::get('memberships/{member}/cf-member', 'MembershipsController@cf_member')->name('memberships.cf.member');
                Route::post('purchase-orders/import', 'PurchaseOrdersController@import')->name('purchase-orders.import');
                Route::resource('purchase-orders', 'PurchaseOrdersController', $edit);
                Route::post('receipted-invoices/import', 'ReceiptedInvoicesController@import')->name('receipted-invoices.import');
                Route::resource('receipted-invoices', 'ReceiptedInvoicesController', $edit);
            });

            Route::middleware('can:delete')->group(function() {
                $delete = ['only' => ['destroy']];

                Route::resource('designations', 'DesignationsController', $delete);
                Route::resource('invoices', 'InvoicesController', $delete);
                Route::resource('members', 'MembersController', $delete);
                Route::resource('memberships', 'MembershipsController', $delete);
                Route::resource('purchase-orders', 'PurchaseOrdersController', $delete);
                Route::resource('receipted-invoices', 'ReceiptedInvoicesController', $delete);
            });

            Route::middleware('can:read')->group(function() {
                $read = ['only' => ['index','show']];

                Route::resource('designations', 'DesignationsController', $read);
                Route::get('invoices/download/{invoice}', 'InvoicesController@download')->name('invoices.download');
                Route::get('invoices/export', 'InvoicesController@export')->name('invoices.export');
                Route::resource('invoices', 'InvoicesController', $read);
                Route::get('members/export', 'MembersController@export')->name('members.export');
                Route::resource('members', 'MembersController', $read);
                Route::get('memberships/export', 'MembershipsController@export')->name('memberships.export');
                Route::resource('memberships', 'MembershipsController', $read);
                Route::get('purchase-orders/export','PurchaseOrdersController@export')->name('purchase-orders.export');
                Route::resource('purchase-orders', 'PurchaseOrdersController', $read);
                Route::get('receipted-invoices/download/{receiptedInvoice}', 'ReceiptedInvoicesController@download')->name('receipted-invoices.download');
                Route::get('receipted-invoices/export', 'ReceiptedInvoicesController@export')->name('receipted-invoices.export');
                Route::resource('receipted-invoices', 'ReceiptedInvoicesController', $read);
            });
        });
    });
});

app/PurchaseOrder.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class PurchaseOrder extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'id',
        'provider',
        'total_amount',
        'VAT',
        'date',
        'signatory_type',
        'signatory_name',
        'signatory_city'
    ];

    public function designations() {
        return $this->hasMany('App\Designation');
    }
}

app/Http/Controllers/Admin/UsersController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Role;
use App\User;
use Auth;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Str;

class UsersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::where('id','<>',auth()->id())->get();
        return view('admin.users.index')->with([
            'users' => $users,
            'count_value' => $users->count()
        ]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function settings()
    {
        return view('admin.settings.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $roles = Role::all();
        return view('admin.users.edit', [
            'roles' => $roles
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'password' => 'required|string|min:8|confirmed'
        ]);

        $user = new User;
        $user->lastname = '';
        $user->firstname = '';
        $user->username = '';
        $user->email = '';
        $user->password = password_hash($request->password, PASSWORD_DEFAULT);
        $user->api_token = Str::random(60);
        return $this->update($request, $user);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        if ($user == Auth::user()) {
            return view('user.settings.show', [
                'user' => $user
            ]);
        }
        return view('admin.users.show')->with('user', $user);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        if ($user == Auth::user()) {
            return view('user.settings.edit', [
                'user' => $user
            ]);
        }
        $roles = Role::all();
        return view('admin.users.edit', [
            'user' => $user,
            'roles' => $roles
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        $request->validate([
            /*'id' => 'required|unique:App\User,id',*/
            'lastname' => 'required|min:2',
            'firstname' => 'required|min:2',
            'username' => 'required|unique:App\User,username,'.$user->id,
            'email' => 'required|email',
        ]);
        $user->save();

        $user->roles()->sync($request->roles);
        $user->lastname = $request->lastname;
        $user->firstname = $request->firstname;
        $user->username = $request->username;
        $user->email = $request->email;
        $user->save();

        return redirect()->route('admin.users.show', $user->id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        $user->roles()->detach();
        $user->delete();

        return redirect()->route('admin.users.index');
    }
}

app/Http/Controllers/User/DesignationsController.php
<?php

namespace App\Http\Controllers\User;

use App\PurchaseOrder;
use App\Designation;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class DesignationsController extends Controller
{
    public function validator($request)
    {
        return $request->validate(
            [
                //'id' => 'required',
                'purchase_order_id' => 'required',
                'name' => 'required',
                'unit_price' => 'required',
                'quantity' => 'required',
                'total_amount' => 'required',
                'note' => 'required'
            ]
        );
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $designations = Designation::all();
        return view('user.designations.index')->with([
            'designations' => $designations,
            'count_value' => $designations->count()
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('user.designations.edit');
    }

    public function cf_purchaseorder(PurchaseOrder $purchaseOrder)
    {
        $designation = new Designation;
        $designation->purchase_order_id = $purchaseOrder->id;
        return view('user.designations.edit')->with([
            'designation' => $designation,
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $designation = new Designation;
        return $this->update($request, $designation);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Designation  $designation
     * @return \Illuminate\Http\Response
     */
    public function show(Designation $designation)
    {
        return view('user.designations.show')->with([
            'designation' => $designation,
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Designation  $designation
     * @return \Illuminate\Http\Response
     */
    public function edit(Designation $designation)
    {
        return view('user.designations.edit')->with([
            'designation' => $designation,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Designation  $designation
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Designation $designation)
    {
        $this->validator($request);
        if (empty($designation->id)) {
            $designation->id = Designation::max('id') +1;
        }
        $designation->purchase_order_id = $request->purchase_order_id;
        $designation->name = $request->name;
        $designation->unit_price = $request->unit_price;
        $designation->quantity = $request->quantity;
        $designation->total_amount = $request->total_amount;
        $designation->note = $request->note;
        $designation->save();

        return redirect()->route('user.designations.show',$designation->id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Designation  $designation
     * @return \Illuminate\Http\Response
     */
    public function destroy(Designation $designation)
    {
        $designation->destroy($designation->id);
        return redirect()->route('user.purchase-orders.show',$designation->purchase_order_id);
    }
}

app/Http/Controllers/User/MembersController.php
<?php

namespace App\Http\Controllers\User;

use App\Exports\MembersExport;
use App\Imports\MembersImport;
use App\Http\Controllers\Controller;
use App\Member;
use App\Membership;
use Illuminate\Http\Request;
use Maatwebsite\Excel\Facades\Excel;

class MembersController extends Controller
{
    public function validator($request)
    {
        return $request->validate(
            [
                'lastname' => 'required',
                'firstname' => 'required',
                'login' => 'nullable',
                'email' => 'nullable',
                'address' => 'nullable',
                'employer' => 'nullable'
            ]
        );
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $members = Member::all();
        return view('user.members.index')->with([
            'members' => $members,
            'count_value' => $members->count()
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('user.members.edit');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $member = new Member;
        return $this->update($request, $member);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Member  $member
     * @return \Illuminate\Http\Response
     */
    public function show(Member $member)
    {
        $memberships = Membership::where('member_id', $member->id)->get();

        return view('user.members.show')->with([
            'member' => $member,
            'memberships' => $memberships,
            'count_value' => $memberships->count()
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Member  $member
     * @return \Illuminate\Http\Response
     */
    public function edit(Member $member)
    {
        return view('user.members.edit')->with([
            'member' => $member,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Member  $member
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Member $member)
    {
        $this->validator($request);

        $member->lastname = $request->lastname;
        $member->firstname = $request->firstname;
        $member->login = $request->login;
        $member->email = $request->email;
        $member->address = $request->address;
        $member->employer = $request->employer;
        $member->save();

        return redirect()->route('user.members.show', $member->id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Member  $member
     * @return \Illuminate\Http\Response
     */
    public function destroy(Member $member)
    {
        foreach ($member->memberships as $membership) {
            $membership->member()->dissociate();
        }
        $member->destroy($member->id);
        return redirect()->route('user.members.index');
    }

    /**
     * Download the resource collection in CSV format
     */
    public function export()
    {
        return Excel::download((new MembersExport()), 'members_'.date('ymdHis').'.csv');
    }

    /**
     * Import the resource in CSV format
     *
     * @param  \Illuminate\Http\Request  $request
     */
    public function import(Request $request)
    {
        if($request->hasFile('file')) {
            try {
                $path = $request->file('file')->getRealPath();
                Excel::import(new MembersImport, $path, null, \Maatwebsite\Excel\Excel::CSV);
            } catch (\Exception $e) {
                \Session::flash('error', $e->getMessage());
            }
        }
        return redirect()->route('user.members.index');
    }
}

resources/views/user/purchaseorders/edit.blade.php
@extends('layouts.default')

@section('javascript')
    {{-- Put here all the links to scripts --}}
@endsection

@section('css')
    {{-- Put here all the links to stylesheet --}}
    <link href="{{ asset('css/buttons.css') }}" rel="stylesheet">
    <link href="{{ asset('css/form.css') }}" rel="stylesheet">
@endsection

@section('content')
<div class="container_page">

    <header>
        <h1>
            @isset($purchaseOrder)
                {{ trans_choice('common.purchase-order', 1)." : ".$purchaseOrder->id }}
            @else
                @lang('common.purchaseorder_creation')
            @endisset
        </h1>
    </header>

    <main>
        <div class="db_infos">
            <form class="buttons_area" method="POST" accept-charset="utf-8">
                @csrf
                @if (Request::is('user/purchase-orders/*/edit'))
                    @method('PATCH')
                @endif

                <div class="case_infos">
                    <label for="provider" class="title">{{ trans_choice('common.provider', 1) }} : </label>
                    <input type="text" id="provider" name="provider" class="@error('provider') is-require @enderror" value="{{ old('provider', $purchaseOrder->provider ?? '') }}" maxlength="256" required>
                </div>
                @error('provider')
                    <span role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror

                <div class="case_infos">
                    <label for="total_amount" class="title">{{ trans_choice('common.total_amount', 1) }} : </label>
                    <input type="number" min="0" max="999999.99" step="0.01" id="total_amount" name="total_amount" value="{{ old('total_amount', $purchaseOrder->total_amount ?? '') }}">
                </div>
                @error('total_amount')
                    <span role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror


                <div class="case_infos">
                    <label for="VAT" class="VAT">{{ trans_choice('common.VAT', 1) }} : </label>
                    <input type="number" min="0" max="999999.99" step="0.01" id="VAT" name="VAT" value="{{ old('VAT', $purchaseOrder->VAT ?? '') }}">
                </div>
                @error('VAT')
                    <span role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror


                <div class="case_infos">
                    <label for="date" class="title">{{ trans_choice('common.date', 1) }} : </label>
                    <input type="date" id="date" name="date" value="{{ old('date', $purchaseOrder->date ?? date('Y-m-d')) }}">
                </div>
                @error('date')
                    <span role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror


                <div class="case_infos">
                    <label for="signatory_type" class="title">{{ trans_choice('common.signatory_type', 1) }} : </label>
                    <input type="text" id="signatory_type" name="signatory_type" value="{{ old('signatory_type', $purchaseOrder->signatory_type ?? '') }}" maxlength="256">
                </div>
                @error('signatory_type')
                    <span role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror


                <div class="case_infos">
                    <label for="signatory_name" class="title">{{ trans_choice('common.signatory_name', 1) }} : </label>
                    <input type="text" id="signatory_name" name="signatory_name" value="{{ old('signatory_name', $purchaseOrder->signatory_name ?? '') }}" maxlength="256">
                </div>
                @error('signatory_name')
                    <span role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror


                <div class="case_infos">
                    <label for="signatory_city" class="title">{{ trans_choice('common.signatory_city', 1) }} : </label>
                    <input type="text" id="signatory_city" name="signatory_city" value="{{ old('signatory_city', $purchaseOrder->signatory_city ?? '') }}" maxlength="256">
                </div>
                @error('signatory_city')
                    <span role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror


                <div>
                    <button type="submit" class="save" formaction="
                        @if (Request::is('user/purchase-orders/*/edit'))
                            {{ route('user.purchase-orders.update', $purchaseOrder->id) }}
                        @else
                            {{ route('user.purchase-orders.store') }}
                        @endif">
                        @lang('buttons.save')
                    </button>
                </div>
            </form>

            <form class="buttons_area" method="GET" accept-charset="utf-8">
                @csrf
                <button type="submit" class="cancel" formaction="
                    @if (Request::is('user/purchase-orders/*/edit'))
                        {{ route('user.purchase-orders.show', $purchaseOrder->id) }}
                    @else
                        {{ route('user.purchase-orders.index') }}
                    @endif">
                    @lang('buttons.cancel')
                </button>
            </form>

        </div>
    </main>
</div>
@endsection

resources/views/user/purchaseorders/index.blade.php
@extends('layouts.default')

@section('javascript')
    {{-- Put here all the links to scripts --}}
    <script src="{{ mix('js/app.js') }}" async defer></script>
    <script type="text/javascript" src="{{ asset('js/tableFilter.js') }}"></script>
    <script type="text/javascript" src="{{ asset('js/tableSorter.js') }}"></script>
@endsection

@section('css')
    {{-- Put here all the links to stylesheet --}}
    <link href="{{ asset('css/buttons.css') }}" rel="stylesheet">
    <link href="{{ asset('css/modal.css') }}" rel="stylesheet">
    <link href="{{ asset('css/tables.css') }}" rel="stylesheet">
@endsection

@section('content')
<div class="container_page">

    <header>
        <h1>{{ trans_choice('common.purchase-order', 2) }}</h1>

    </header>

    <main>
        <input type="text" id="inputFilter" placeholder="@lang('common.research')" title="@lang('common.type_here')">

        <div class="container_table">
            <div class="table" id="table">
                <div class="row header">
                    <div class="cell short">
                        <p>{{ trans_choice('common.id', $count_value) }}</p>
                    </div>
                    <div class="cell medium">
                        <p>{{ trans_choice('common.provider', $count_value) }}</p>
                    </div>
                    <div class="cell medium">
                        <p>{{ trans_choice('common.total_amount', $count_value) }}</p>
                    </div>
                    <div class="cell short">
                        <p>{{ trans_choice('common.VAT', $count_value) }}</p>
                    </div>
                    <div class="cell medium">
                        <p>{{ trans_choice('common.date', $count_value) }}</p>
                    </div>
                    <div class="cell large">
                        <p>{{ trans_choice('common.signatory_name', $count_value) }}</p>
                    </div>
                    @can('delete')
                    <div class="cell options">
                        <p>{{ trans_choice('common.action', 2) }}</p>
                    </div>
                    @endcan
                </div>
                @foreach ($purchaseOrders as $purchaseOrder)
                    <div class="row">
                        <a href="{{ route('user.purchase-orders.show', $purchaseOrder->id)}}">
                            <div class="cell short" data-title="{{ trans_choice('common.purchase-order', 1) }}">
                                <p>{{ $purchaseOrder->id}}</p>
                            </div>
                            <div class="cell medium" data-title="{{ trans_choice('common.provider', 1) }}">
                                <p>{{ $purchaseOrder->provider}}</p>
                            </div>
                            <div class="cell medium" data-title="{{ trans_choice('common.total_amount', 1) }}">
                                <p>{{ $purchaseOrder->total_amount}}</p>
                            </div>
                            <div class="cell short" data-title="{{ trans_choice('common.VAT', 1) }}">
                                <p>{{ $purchaseOrder->VAT}}</p>
                            </div>
                            <div class="cell medium" data-title="{{ trans_choice('common.date', 1) }}">
                                <p>{{ $purchaseOrder->date}}</p>
                            </div>
                            <div class="cell large" data-title="{{ trans_choice('common.signatory_name', 1) }}">
                                <p>{{ $purchaseOrder->signatory_name}}</p>
                            </div>
                        </a>
                        @can('edit', 'delete')
                            <div class="cell options" data-title="{{ trans_choice('common.setting', 2) }}">
                                <div class="container-icon">
                                    @can('edit')
                                        <form class="ico" method="GET" accept-charset="utf-8" action="{{ route('user.purchase-orders.edit', $purchaseOrder->id) }}">
                                            @csrf
                                            <button type="submit" >
                                                <img src="{{ asset('images/edit_icon.svg') }}" alt="Edit icon">
                                            </button>
                                        </form>
                                    @endcan

                                    @can('delete')
                                        <form class="ico" method="POST" accept-charset="utf-8" action="{{ route('user.purchase-orders.destroy', $purchaseOrder->id) }}">
                                            @csrf
                                            @method('DELETE')
                                            <confirm_action src="{{ asset('images/delete_icon.svg') }}">
                                            </confirm_action>
                                        </form>
                                    @endcan
                                </div>
                            </div>
                        @endcan

                    </div>
                @endforeach
            </div>
        </div>

        <div class="buttons_area">
            @can('edit')
                <a href="{{ route('user.purchase-orders.create') }}">
                    <button class="create">
                        @lang('buttons.add')
                        <img src="{{ asset('images/plus_icon.svg') }}" alt="Plus icon">
                    </button>
                </a>

                <div class="file_color">
                    <form method="post" accept-charset="utf-8" enctype="multipart/form-data">
                        @csrf
                        <input type="file" name="file">
                        <button class="import no-margin" type="submit" formaction="{{ route('user.purchase-orders.import') }}">
                            @lang('buttons.import')
                            <img src="{{ asset('images/plus_icon.svg') }}" alt="Plus icon">
                        </button>
                    </form>
                </div>
            @endcan

            @can('read')
                <a href="{{ route('user.purchase-orders.export') }}">
                    <button class="export">
                        @lang('buttons.export')
                        <img src="{{ asset('images/download_icon.svg') }}" alt="Download icon">
                    </button>
                </a>
            @endcan
        </div>

    </main>
</div>
@endsection